### PR TITLE
only call next once

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by bucaran** [comment]
Why would you call `next` more than once?

I don't understand this.

**Comment by calvinmetcalf** [comment]
Currently of somebody calls next the promise will also call next. 

E. G. We want to avoid calling next twice

**Comment by bucaran** [comment]
I see! If somebody calls next and then `returns` a value different from `undefined`

```js
  if (undefined !== result) {
    Promise.resolve(result).then(push, next)
  }
...
```
 the Promise will also call next.

Thanks! Let me go over this as soon as I hace a chance.

**Comment by bucaran** [comment]
:+1: Great!

**Pull request merged**
